In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census

# Census API Key
from config import api_key
c = Census(api_key, year=2015)

In [6]:
census_data = c.acs5.get(("NAME", "B19013_001E", "B01003_001E", "B01002_001E",
                          "B19301_001E",
                          "B17001_002E", "B25034_010E"), {'for': 'zip code tabulation area:*'})


census_pd = pd.DataFrame(census_data)

census_pd = census_pd.rename(columns={"B01003_001E": "Population",
                                      "B01002_001E": "Median Age",
                                      "B19013_001E": "Household Income",
                                      "B19301_001E": "Per Capita Income",
                                      "B17001_002E": "Poverty Count",
                                      "B25034_010E": "State",
                                      "NAME": "Name", "zip code tabulation area": "Zipcode"})

census_pd["Poverty Rate"] = 100 * \
    census_pd["Poverty Count"].astype(
        int) / census_pd["Population"].astype(int)


census_pd = census_pd[["Zipcode", "Population", "Median Age", "Household Income",
                       "Per Capita Income", "Poverty Count", "State", "Poverty Rate"]]


print(len(census_pd))
census_pd.head()

33120

,Zipcode,Population,Median Age,Household Income,Per Capita Income,Poverty Count,State,Poverty Rate
0,12810,724.0,46.5,57500.0,25551.0,78.0,28.0,10.773481
1,12811,67.0,45.9,-666666666.0,11590.0,0.0,7.0,0.000000
2,12812,58.0,64.1,49583.0,23600.0,0.0,62.0,0.000000
3,12814,1282.0,46.4,58176.0,35508.0,51.0,73.0,3.978159
4,12815,1103.0,54.2,60458.0,30685.0,159.0,78.0,14.415231

In [7]:
census_pd.to_csv("Data/2015_census_data.csv", index=False)